//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamAnhNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.Homework = new HashSet<Homework>();
            this.MadeMistakes = new HashSet<MadeMistake>();
        }
    
        public string ClassId { get; set; }
        public int ClassNumber { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public string Location { get; set; }
        public string LessionContent { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public string HomeworkQuestion { get; set; }
        public string SupportMaterial { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Homework> Homework { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MadeMistake> MadeMistakes { get; set; }
    }
}
