//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamAnhNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MadeMistake
    {
        public string MistakeId { get; set; }
        public string StudentUsername { get; set; }
        public string ClassId { get; set; }
        public int ClassNumber { get; set; }
        public Nullable<bool> IsPay { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Mistake Mistake { get; set; }
        public virtual Register Register { get; set; }
    }
}
