//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamAnhNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string ClassId { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
