//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamAnhNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mistake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mistake()
        {
            this.MadeMistakes = new HashSet<MadeMistake>();
        }
    
        public string MistakeId { get; set; }
        public string Description { get; set; }
        public Nullable<long> Charge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MadeMistake> MadeMistakes { get; set; }
    }
}
